name: Deploy nodejs API to AWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: |
          docker build \
          --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
          --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --build-arg DYNAMODB_TABLE_NAME=${{ secrets.DYNAMODB_TABLE_NAME }} \
          --build-arg RDS_INSTANCE_IDENTIFIER=${{ secrets.RDS_INSTANCE_IDENTIFIER }} \
          --build-arg RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
          --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
          --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
          --build-arg S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
          -t alvin1979/nodejs-api-aws .
      - name: Publish image to docker hub
        run: docker push alvin1979/nodejs-api-aws:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: save private key to a file
        run: | 
          echo $PRIVATE_KEY > private-key.pem
          chmod 600 private-key.pem
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pull image from docker hub and deploy to EC2
        env:
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USERNAME}}
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem ${USER_NAME}@${HOSTNAME} '
            # Pull the latest Docker image
            docker pull alvin1979/nodejs-api-aws:latest
            docker run -d -p 5000:5000 \
            --name nodejs-notes-app-container \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e DYNAMODB_TABLE_NAME=${{ secrets.DYNAMODB_TABLE_NAME }} \
            -e RDS_INSTANCE_IDENTIFIER=${{ secrets.RDS_INSTANCE_IDENTIFIER }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            alvin1979/nodejs-api-aws
          '
